
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/team01-s24-5pm-7
owner: ucsb-cs156-s24
repo_name: team01-s24-5pm-7
pull_requests: [{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"AdilAhmed-Tides-Controller","number":21,"title":"Adil ahmed tides controller","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-7/pull/21"},{"author":{"id":"U_kgDOBh2uuQ","is_bot":false,"login":"adilahmed2","name":"Adil Ahmed"},"headRefName":"AdilAhmed-Tides","number":20,"title":"Adil Ahmed tides","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-7/pull/20"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June-Joke-Controller","number":19,"title":"Add Joke Controller and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-7/pull/19"},{"author":{"id":"U_kgDOBnFUwg","is_bot":false,"login":"zhenbi93","name":""},"headRefName":"June","number":18,"title":"Add Joke Service and Tests","url":"https://github.com/ucsb-cs156-s24/team01-s24-5pm-7/pull/18"}]
